on:
  push:
    # branches:
    #   -main
    #   -beta

# permissions:
#   contents: write

jobs:
  # get-version:
  #    uses: shiipou/github-actions/.github/workflows/get-version.yml@main

  Install-rust:
    name: Install rust
    runs-on: ubuntu-latest
    # if: ${{ needs.get-version.outputs.will-release == 'true' }}
    # needs:
    #   - get-version
    steps:
      # - name: Print version
      #   run: |
      #    echo "${{ needs.get-version.outputs.version }}"
      #    echo "${{ needs.get-version.outputs.changelogs }}"
      #    echo "${{ needs.get-version.outputs.is-pre-release }}"
      #    echo "${{ needs.get-version.outputs.will-release }}"
      - name: Setup Rust
        uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      # - name: Setup trunk
      #   uses: trunk-io/trunk-action@v1.1.14
      # - name: Run WASM
      #   run: trunk build --release
      - name: check rust version
        run: rustc --version
      - name: check rustup
        run: rustup --version
      - name: install WASM
        run: rustup target add wasm32-unknown-unknown
      - name: install trunk
        uses: jetli/trunk-action@v0.5.0

      
        
      
  
