on:
  push:
    branches:
      -main
      -beta

permissions:
  contents: write

jobs:
  get-version:
     uses: shiipou/github-actions/.github/workflows/get-version.yml@main

  build:
    name: Rust build
    runs-on: ubuntu-latest
    if: ${{ needs.get-version.outputs.will-release == 'true' }}
    needs:
      - get-version
    steps:
      - name: Print version
        run: |
         echo "${{ needs.get-version.outputs.version }}"
         echo "${{ needs.get-version.outputs.changelogs }}"
         echo "${{ needs.get-version.outputs.is-pre-release }}"
         echo "${{ needs.get-version.outputs.will-release }}"
      #- name: Setup trunk
      #  uses: trunk-io/trunk-action@bd686325615e9cf5a4ef98372ba94a472f9b5238
      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
      
        
      
  
